### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by ghost** [mixandjam/StarFox-RailMovement#1]
Until a license is added all the code in this repository is considered copyrighted. Something like https://choosealicense.com/ can be used to determine which license to use for this project. I would recommend the MIT license.

**Comment by mixandjam** [comment]
Thanks for the heads up @rogersachan!
Just added the license!

**Comment by ghost** [comment]
@mixandjam is it possible that your other repos can be updated with the MIT license as well? thanks again!

**Comment by mixandjam** [comment]
@rogersachan updated!
